# Generated by Django 5.2 on 2025-07-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WheelSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(db_index=True, max_length=255, unique=True)),
                ('submitted_by', models.CharField(max_length=255)),
                ('submitted_date', models.DateField()),
                ('fields', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wheel Specification',
                'verbose_name_plural': 'Wheel Specifications',
                'ordering': ['-submitted_date'],
            },
        ),
    ]
